/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AccountManager = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const RateCardItem = IDL.Record({
  'id' : IDL.Text,
  'subcategory' : IDL.Text,
  'category' : IDL.Text,
  'detailedDescription' : IDL.Text,
  'standardCost' : IDL.Float64,
  'itemRefNo' : IDL.Text,
  'opsBriskCost' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AnalysisItem = IDL.Record({
  'id' : IDL.Text,
  'total' : IDL.Float64,
  'duration' : IDL.Nat,
  'subcategory' : IDL.Text,
  'marginPercentage' : IDL.Float64,
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
  'margin' : IDL.Float64,
  'detailedDescription' : IDL.Text,
  'standardCost' : IDL.Float64,
  'itemRefNo' : IDL.Text,
  'opsBriskCost' : IDL.Float64,
});
export const AnalysisSummary = IDL.Record({
  'totalProfit' : IDL.Float64,
  'totalMargin' : IDL.Float64,
  'items' : IDL.Vec(AnalysisItem),
});
export const QuoteHeader = IDL.Record({
  'projectDuration' : IDL.Text,
  'projectName' : IDL.Text,
  'clientName' : IDL.Text,
  'accountManager' : IDL.Text,
});
export const QuoteItem = IDL.Record({
  'id' : IDL.Text,
  'total' : IDL.Float64,
  'duration' : IDL.Nat,
  'subcategory' : IDL.Text,
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
  'detailedDescription' : IDL.Text,
  'standardCost' : IDL.Float64,
  'itemRefNo' : IDL.Text,
  'opsBriskCost' : IDL.Float64,
});
export const FullQuote = IDL.Record({
  'total' : IDL.Float64,
  'items' : IDL.Vec(QuoteItem),
  'header' : QuoteHeader,
});
export const Quote = IDL.Record({
  'total' : IDL.Float64,
  'items' : IDL.Vec(QuoteItem),
});
export const AccountManagerList = IDL.Record({
  'managers' : IDL.Vec(AccountManager),
});
export const UserProfile = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'accountManagerId' : IDL.Text,
  'phone' : IDL.Text,
});
export const QuoteHistoryItem = IDL.Record({
  'id' : IDL.Text,
  'total' : IDL.Float64,
  'timestamp' : IDL.Int,
  'items' : IDL.Vec(QuoteItem),
  'header' : QuoteHeader,
});
export const RateCard = IDL.Record({ 'items' : IDL.Vec(RateCardItem) });
export const UploadedFile = IDL.Record({
  'id' : IDL.Text,
  'contentType' : IDL.Text,
  'name' : IDL.Text,
  'size' : IDL.Nat,
  'blobId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addAccountManager' : IDL.Func([AccountManager], [], []),
  'addRateCardItem' : IDL.Func([RateCardItem], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAccountManager' : IDL.Func([IDL.Text], [], []),
  'deleteRateCardItem' : IDL.Func([IDL.Text], [], []),
  'generateAnalysis' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Nat))],
      [AnalysisSummary],
      [],
    ),
  'generateFullQuote' : IDL.Func(
      [QuoteHeader, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Nat))],
      [FullQuote],
      [],
    ),
  'generateQuote' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Nat))],
      [Quote],
      [],
    ),
  'getAccountManagers' : IDL.Func([], [AccountManagerList], ['query']),
  'getAllRateCardItems' : IDL.Func([], [IDL.Vec(RateCardItem)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getQuoteHistory' : IDL.Func([], [IDL.Vec(QuoteHistoryItem)], ['query']),
  'getQuoteHistoryItem' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(QuoteHistoryItem)],
      ['query'],
    ),
  'getRateCard' : IDL.Func([], [RateCard], ['query']),
  'getRateCardItem' : IDL.Func([IDL.Text], [IDL.Opt(RateCardItem)], ['query']),
  'getUploadedFiles' : IDL.Func([], [IDL.Vec(UploadedFile)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'trackUploadedFile' : IDL.Func([UploadedFile], [], []),
  'updateAccountManager' : IDL.Func([AccountManager], [], []),
  'updateAccountManagers' : IDL.Func([IDL.Vec(AccountManager)], [], []),
  'updateRateCard' : IDL.Func([IDL.Vec(RateCardItem)], [], []),
  'updateRateCardItem' : IDL.Func([RateCardItem], [], []),
  'updateStandardCost' : IDL.Func([IDL.Text, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AccountManager = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const RateCardItem = IDL.Record({
    'id' : IDL.Text,
    'subcategory' : IDL.Text,
    'category' : IDL.Text,
    'detailedDescription' : IDL.Text,
    'standardCost' : IDL.Float64,
    'itemRefNo' : IDL.Text,
    'opsBriskCost' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AnalysisItem = IDL.Record({
    'id' : IDL.Text,
    'total' : IDL.Float64,
    'duration' : IDL.Nat,
    'subcategory' : IDL.Text,
    'marginPercentage' : IDL.Float64,
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
    'margin' : IDL.Float64,
    'detailedDescription' : IDL.Text,
    'standardCost' : IDL.Float64,
    'itemRefNo' : IDL.Text,
    'opsBriskCost' : IDL.Float64,
  });
  const AnalysisSummary = IDL.Record({
    'totalProfit' : IDL.Float64,
    'totalMargin' : IDL.Float64,
    'items' : IDL.Vec(AnalysisItem),
  });
  const QuoteHeader = IDL.Record({
    'projectDuration' : IDL.Text,
    'projectName' : IDL.Text,
    'clientName' : IDL.Text,
    'accountManager' : IDL.Text,
  });
  const QuoteItem = IDL.Record({
    'id' : IDL.Text,
    'total' : IDL.Float64,
    'duration' : IDL.Nat,
    'subcategory' : IDL.Text,
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
    'detailedDescription' : IDL.Text,
    'standardCost' : IDL.Float64,
    'itemRefNo' : IDL.Text,
    'opsBriskCost' : IDL.Float64,
  });
  const FullQuote = IDL.Record({
    'total' : IDL.Float64,
    'items' : IDL.Vec(QuoteItem),
    'header' : QuoteHeader,
  });
  const Quote = IDL.Record({
    'total' : IDL.Float64,
    'items' : IDL.Vec(QuoteItem),
  });
  const AccountManagerList = IDL.Record({
    'managers' : IDL.Vec(AccountManager),
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'accountManagerId' : IDL.Text,
    'phone' : IDL.Text,
  });
  const QuoteHistoryItem = IDL.Record({
    'id' : IDL.Text,
    'total' : IDL.Float64,
    'timestamp' : IDL.Int,
    'items' : IDL.Vec(QuoteItem),
    'header' : QuoteHeader,
  });
  const RateCard = IDL.Record({ 'items' : IDL.Vec(RateCardItem) });
  const UploadedFile = IDL.Record({
    'id' : IDL.Text,
    'contentType' : IDL.Text,
    'name' : IDL.Text,
    'size' : IDL.Nat,
    'blobId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addAccountManager' : IDL.Func([AccountManager], [], []),
    'addRateCardItem' : IDL.Func([RateCardItem], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAccountManager' : IDL.Func([IDL.Text], [], []),
    'deleteRateCardItem' : IDL.Func([IDL.Text], [], []),
    'generateAnalysis' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Nat))],
        [AnalysisSummary],
        [],
      ),
    'generateFullQuote' : IDL.Func(
        [QuoteHeader, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Nat))],
        [FullQuote],
        [],
      ),
    'generateQuote' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Nat))],
        [Quote],
        [],
      ),
    'getAccountManagers' : IDL.Func([], [AccountManagerList], ['query']),
    'getAllRateCardItems' : IDL.Func([], [IDL.Vec(RateCardItem)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getQuoteHistory' : IDL.Func([], [IDL.Vec(QuoteHistoryItem)], ['query']),
    'getQuoteHistoryItem' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(QuoteHistoryItem)],
        ['query'],
      ),
    'getRateCard' : IDL.Func([], [RateCard], ['query']),
    'getRateCardItem' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(RateCardItem)],
        ['query'],
      ),
    'getUploadedFiles' : IDL.Func([], [IDL.Vec(UploadedFile)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'trackUploadedFile' : IDL.Func([UploadedFile], [], []),
    'updateAccountManager' : IDL.Func([AccountManager], [], []),
    'updateAccountManagers' : IDL.Func([IDL.Vec(AccountManager)], [], []),
    'updateRateCard' : IDL.Func([IDL.Vec(RateCardItem)], [], []),
    'updateRateCardItem' : IDL.Func([RateCardItem], [], []),
    'updateStandardCost' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };