/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccountManager {
  'id' : string,
  'name' : string,
  'email' : [] | [string],
}
export interface AccountManagerList { 'managers' : Array<AccountManager> }
export interface AnalysisItem {
  'id' : string,
  'total' : number,
  'duration' : bigint,
  'subcategory' : string,
  'marginPercentage' : number,
  'quantity' : bigint,
  'category' : string,
  'margin' : number,
  'detailedDescription' : string,
  'standardCost' : number,
  'itemRefNo' : string,
  'opsBriskCost' : number,
}
export interface AnalysisSummary {
  'totalProfit' : number,
  'totalMargin' : number,
  'items' : Array<AnalysisItem>,
}
export interface FullQuote {
  'total' : number,
  'items' : Array<QuoteItem>,
  'header' : QuoteHeader,
}
export interface Quote { 'total' : number, 'items' : Array<QuoteItem> }
export interface QuoteHeader {
  'projectDuration' : string,
  'projectName' : string,
  'clientName' : string,
  'accountManager' : string,
}
export interface QuoteHistoryItem {
  'id' : string,
  'total' : number,
  'timestamp' : bigint,
  'items' : Array<QuoteItem>,
  'header' : QuoteHeader,
}
export interface QuoteItem {
  'id' : string,
  'total' : number,
  'duration' : bigint,
  'subcategory' : string,
  'quantity' : bigint,
  'category' : string,
  'detailedDescription' : string,
  'standardCost' : number,
  'itemRefNo' : string,
  'opsBriskCost' : number,
}
export interface RateCard { 'items' : Array<RateCardItem> }
export interface RateCardItem {
  'id' : string,
  'subcategory' : string,
  'category' : string,
  'detailedDescription' : string,
  'standardCost' : number,
  'itemRefNo' : string,
  'opsBriskCost' : number,
}
export interface UploadedFile {
  'id' : string,
  'contentType' : string,
  'name' : string,
  'size' : bigint,
  'blobId' : string,
}
export interface UserProfile {
  'id' : string,
  'name' : string,
  'email' : string,
  'accountManagerId' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addAccountManager' : ActorMethod<[AccountManager], undefined>,
  'addRateCardItem' : ActorMethod<[RateCardItem], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAccountManager' : ActorMethod<[string], undefined>,
  'deleteRateCardItem' : ActorMethod<[string], undefined>,
  'generateAnalysis' : ActorMethod<
    [Array<[string, bigint, bigint]>],
    AnalysisSummary
  >,
  'generateFullQuote' : ActorMethod<
    [QuoteHeader, Array<[string, bigint, bigint]>],
    FullQuote
  >,
  'generateQuote' : ActorMethod<[Array<[string, bigint, bigint]>], Quote>,
  'getAccountManagers' : ActorMethod<[], AccountManagerList>,
  'getAllRateCardItems' : ActorMethod<[], Array<RateCardItem>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getQuoteHistory' : ActorMethod<[], Array<QuoteHistoryItem>>,
  'getQuoteHistoryItem' : ActorMethod<[string], [] | [QuoteHistoryItem]>,
  'getRateCard' : ActorMethod<[], RateCard>,
  'getRateCardItem' : ActorMethod<[string], [] | [RateCardItem]>,
  'getUploadedFiles' : ActorMethod<[], Array<UploadedFile>>,
  'getUserProfile' : ActorMethod<[string], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'trackUploadedFile' : ActorMethod<[UploadedFile], undefined>,
  'updateAccountManager' : ActorMethod<[AccountManager], undefined>,
  'updateAccountManagers' : ActorMethod<[Array<AccountManager>], undefined>,
  'updateRateCard' : ActorMethod<[Array<RateCardItem>], undefined>,
  'updateRateCardItem' : ActorMethod<[RateCardItem], undefined>,
  'updateStandardCost' : ActorMethod<[string, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];